# Generated by Django 5.2.3 on 2025-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strongTo', models.ManyToManyField(related_name='strong_against', to='pokemon.type')),
                ('weakTo', models.ManyToManyField(related_name='weak_against', to='pokemon.type')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.ManyToManyField(to='pokemon.type')),
            ],
        ),
    ]
