# Generated by Django 5.2.3 on 2025-06-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='strongTo',
            field=models.ManyToManyField(blank=True, related_name='strong_against', to='pokemon.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='weakTo',
            field=models.ManyToManyField(blank=True, related_name='weak_against', to='pokemon.type'),
        ),
    ]
